Lab.ControleContatos.Mvc/ControleContatos.MVC/Controllers/AlterarSenhaController.cs
using ControleContatos.MVC.Helper;
using ControleContatos.MVC.Interfaces;
using ControleContatos.MVC.Models;
using ControleUsuarios.MVC.Repository;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ControleContatos.MVC.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepository usuarioRepository,
                                        ISessao sessao)
        {
            _usuarioRepository = usuarioRepository;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.GetSessaoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                if (ModelState.IsValid)
                {
                    _usuarioRepository.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }
                return View("Index", alterarSenhaModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar sua senha, tente novamente. Detalhe do erro:{erro.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

Lab.ControleContatos.Mvc/ControleContatos.MVC/Views/AlterarSenha/Index.cshtml
@using ControleContatos.MVC.Enums
@model AlterarSenhaModel
@{
    ViewData["Title"] = "Alterar senha do usuario";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<div class="text-center">
    <h1 class="display-4">Alterar senha do usuario</h1>
</div>

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">
    <div class="form-group">
        <label for="senhaAtual">Senha atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual">
        @Html.ValidationMessageFor(x => x.SenhaAtual)
    </div>
    <br />
    <div class="form-group">
        <label for="novaSenha">Nova senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha atual">
        @Html.ValidationMessageFor(x => x.NovaSenha)
    </div>
    <br />
    <div class="form-group">
        <label for="confirmarSenha">Confirmar senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Confirme a nova senha">
        @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
    </div>
    <br />

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Home" asp-action="Index" role="button">Voltar</a>
</form>