Lab.ControleContatos.Mvc/ControleContatos.MVC/Controllers/ContatoController.cs
using ControleContatos.MVC.Filters;
using ControleContatos.MVC.Helper;
using ControleContatos.MVC.Interfaces;
using ControleContatos.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace ControleContatos.MVC.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ContatoController : Controller
    {
        private readonly IContatoRepository _contatoRepository;
        private readonly ISessao _sessao;
        
        public ContatoController(IContatoRepository contatoRepository,
                                ISessao sessao)
        {
            _contatoRepository = contatoRepository;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.GetSessaoUsuario();
            List<ContatoModel> contatos = _contatoRepository.BuscarTodos(usuarioLogado.Id);
            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepository.ListarPorId(id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepository.ListarPorId(id);
            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepository.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar seu contato";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamente. Detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.GetSessaoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;
                    _contatoRepository.Adicionar(contato);

                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(contato);

            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu contato, tente novamente. Detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.GetSessaoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;

                    _contatoRepository.Atualizar(contato);

                    TempData["MensagemSucesso"] = "Contato editado com sucesso";
                    return RedirectToAction("Index");
                }
                return View("Editar", contato);
            }
            catch (Exception erro)
            {

                TempData["MensagemErro"] = $"Ops, não conseguimos editar seu contato, tente novamente. Detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Lab.ControleContatos.Mvc/ControleContatos.MVC/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmação apagar o contato";
}

<div class="text-center">
    <h3>Realmente deseja apagar o contato (@Model.Nome)?</h3>
    <br />

    <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
    <a class="btn btn-danger" role="button" asp-controller="Contato" asp-route-id="@Model.Id" asp-action="Apagar">Confirmar exclusão</a>
</div>

Lab.ControleContatos.Mvc/ControleContatos.MVC/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Criar contato";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar contato</h1>
</div>

<form asp-controller="Contato" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
    </div> 
    <br/>
    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o email do contato">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <br/>
    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular do contato">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>
    <br />

    <button type="submit" class="btn btn-primary btn-block">Criar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

Lab.ControleContatos.Mvc/ControleContatos.MVC/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar contato";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar contato</h1>
</div>

<form asp-controller="Contato" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <br />
    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o email do contato">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <br />
    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular do contato">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>
    <br />

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

Lab.ControleContatos.Mvc/ControleContatos.MVC/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de contatos";
}

<div class="text-center">

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Listagem de contatos</h1>

    <div class="d-grip gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">+</a>
    </div>

    <table class="table table-hover" id="table-contatos">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Celular</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any())
            {
                foreach(ContatoModel contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Celular</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar" asp-route-id="@contato.Id">Editar</a>
                                <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao" asp-route-id="@contato.Id">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum contato encontrado</td></tr>
            }
        </tbody>
    </table>
</div>